FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["src/MiProyecto/MiProyecto.csproj", "src/MiProyecto/"]
RUN dotnet restore "src/MiProyecto/MiProyecto.csproj"
COPY . .
WORKDIR "/src/src/MiProyecto"
RUN dotnet build "MiProyecto.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MiProyecto.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MiProyecto.dll"]
