services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MiBaseDatos;User Id=sa;Password=YourPassword123!;TrustServerCertificate=true;"
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - app-network

volumes:
  sqldata:

networks:
  app-network:
    driver: bridge
